version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'husky'
        versions: ['5.x']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
