name: "Github Action Merge Dependabot"
description: "Automatically approve and merge dependabot PRs"
inputs:
  github-token:
    description: "A GitHub token"
    required: true
  exclude:
    description: "Packages that you want to manually review before upgrading"
    required: false
  approve-only:
    description: "If true, the PR is only approved but not merged"
    required: false
    default: false
  merge-method:
    description: "The merge method you would like to use (squash, merge, rebase)"
    required: false
    default: "squash"
  merge-comment:
    description: "An arbitrary message that you'd like to comment on the PR after it gets auto-merged"
    required: false
    default: ""
runs:
  using: "node12"
  main: "src/index.js"
