name: 'Github Action Merge Dependabot'
description: 'Automatically approve and merge dependabot PRs'

runs:
  using: 'composite'
  steps:
    - name: Fetch metadata
      uses: dependabot/fetch-metadata@v1
    - name: Merge/approve PR
      uses: actions/github-script@v6
      if: ${{ github.event_name == 'pull_request' }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require('${{ github.action_path }}/dist/index.js')
          await script({ github, context, inputs: ${{ toJSON(inputs) }} })

branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
