name: Check linked issues

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    permissions:
        issues: read
        pull-requests: write
    name: Check linked issues
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@7140e2e01aa0c18b8ac61bddf5e89abde1ca760e # v1.8.3
        id: check-linked-issues
        with:
          github-token: ${{ github.token }}
          exclude-branches: "release/**, dependabot/**"
